---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kalamajakapital-scheduler-configmap
  namespace: kube-system
  labels:
    app.kubernetes.io/name: kalamajakapital-scheduler
    app.kubernetes.io/version: "0.1.0-alpha2"
    app.kubernetes.io/component: scheduler
    app.kubernetes.io/part-of: core-infra
    kalamajakapital.ee/tier: "0"
    kalamajakapital.ee/team: platform
data:
  scheduler.config.yaml: |
    ---
    schedulerName: kalamajakapital.ee/workload-scheduler
    selectionCriteria:
      kalamajakapital.ee/min-containerd-version: ["v1.11", "v1.12"]
      kalamajakapital.ee/min-kubelet-version: ["v1.3", "v1.4"]
  scheduler.logging.yaml: |
    ---
    # Normally I'd use a formatter that standardises logs:
    # https://github.com/transferwise/cloudflare-prometheus-exporter/blob/master/cloudflare_exporter/logging.py
    version: 1
    formatters:
      json:
        class: pythonjsonlogger.jsonlogger.JsonFormatter
    handlers:
      console:
        class: logging.StreamHandler
        level: INFO
        formatter: json
        stream: ext://sys.stdout
    disable_existing_loggers: false
    loggers:
      stdout:
        level: INFO
        handlers: [console]
        propagate: false
        formatter: json
        stream: ext://sys.stdout
    root:
      level: INFO
      handlers: [console]
